<?php

declare(strict_types=1);

namespace OnPay;

use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use OnPay\API\Exception\ApiException;
use OnPay\API\Exception\ConnectionException;
use OnPay\API\Exception\TokenException;
use OnPay\API\GatewayService;
use OnPay\API\PaymentService;
use OnPay\API\SubscriptionService;
use OnPay\API\TransactionService;
use OnPay\Auth\TokenManager;
use OnPay\Http\ApiClient;
use OnPay\Http\ApiClientInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Log\LoggerAwareInterface;
use Psr\Log\LoggerInterface;
use TomSommer\OAuth2\Client\Provider\OnPay as OnPayProvider;

/**
 * Entry point to the OnPay API.
 *
 * Turns the option array into the three collaborators that do the work - the
 * OAuth provider, the token manager and the API client - and hands out the
 * service objects for each part of the API.
 */
class OnPayAPI implements LoggerAwareInterface {
    const SDK_VERSION = '3.2.0';

    protected string $scope = 'full';

    protected OnPayProvider $oauth2Provider;

    protected TokenManager $tokenManager;

    protected ApiClient $apiClient;

    protected ?TransactionService $transactionService = null;

    protected ?SubscriptionService $subscriptionService = null;

    protected ?PaymentService $paymentService = null;

    protected ?GatewayService $gatewayService = null;

    /**
     * The optional PSR-18 $httpClient (with PSR-17 $requestFactory and $streamFactory)
     * routes all API requests through any PSR-18 compatible HTTP client: Symfony
     * HttpClient, Guzzle, Buzz and so on. All parameters are typed so DI containers
     * can autowire registered services automatically. When they are omitted, the
     * client and factories are auto-discovered from the installed packages.
     *
     * @param array $options
     * @param ClientInterface|null $httpClient PSR-18 HTTP client
     * @param RequestFactoryInterface|null $requestFactory PSR-17 request factory
     * @param StreamFactoryInterface|null $streamFactory PSR-17 stream factory
     * @param LoggerInterface|null $logger PSR-3 logger for failed responses
     */
    public function __construct(
        TokenStorageInterface $tokenStorage,
        array $options,
        ?ClientInterface $httpClient = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?LoggerInterface $logger = null
    ) {
        $options = $this->resolveOptions($tokenStorage, $options);

        $httpClient ??= Psr18ClientDiscovery::find();
        $requestFactory ??= Psr17FactoryDiscovery::findRequestFactory();
        $streamFactory ??= Psr17FactoryDiscovery::findStreamFactory();

        $this->oauth2Provider = new OnPayProvider(
            [
                'clientId' => $options['client_id'],
                'redirectUri' => $options['redirect_uri'],
                'gatewayId' => isset($options['gateway_id']) ? (string) $options['gateway_id'] : null,
                'baseAuthorizeUri' => $options['base_authorize_uri'],
                'baseUri' => $options['base_uri'],
                'scopes' => [$this->scope],
                'pkceMethod' => $options['pkce_method'] ?? null,
            ],
            $this->providerCollaborators($httpClient)
        );

        $this->tokenManager = new TokenManager($tokenStorage, $this->oauth2Provider);

        $this->apiClient = new ApiClient(
            $httpClient,
            $requestFactory,
            $streamFactory,
            $this->tokenManager,
            $options['base_uri'],
            $options['platform'],
            $logger,
        );
    }

    /**
     * The client used for API requests, for callers that need an endpoint the
     * service classes do not cover yet.
     */
    public function getApiClient(): ApiClientInterface {
        return $this->apiClient;
    }

    /**
     * Sets a PSR-3 logger that receives failed responses.
     */
    public function setLogger(LoggerInterface $logger): void {
        $this->apiClient->setLogger($logger);
    }

    /**
     * Returns the OAuth 2.0 provider, so consumers can drive the authorization
     * flow themselves when the convenience methods are not enough.
     */
    public function getProvider(): OnPayProvider {
        return $this->oauth2Provider;
    }

    /**
     * The PKCE code verifier generated by the last authorize() call. Only set
     * when the 'pkce_method' option is in use. Persist it alongside the OAuth
     * state and hand it back with setPkceCode() before finishAuthorize().
     */
    public function getPkceCode(): ?string {
        return $this->oauth2Provider->getPkceCode();
    }

    /**
     * Restores the PKCE code verifier obtained from getPkceCode().
     */
    public function setPkceCode(string $pkceCode): void {
        $this->oauth2Provider->setPkceCode($pkceCode);
    }

    /**
     * Checks if we have a Token that looks valid.
     * If it looks valid, we'll attempt to ping the API.
     */
    public function isAuthorized(): bool {
        // If we're able to ping the API, we're authorized.
        try {
            $this->ping();
            return true;
        } catch (TokenException $e) {
            return false;
        }
    }

    /**
     * Returns the platform value set.
     */
    public function getPlatform(): string {
        return $this->apiClient->getPlatform();
    }

    /**
     * Returns a URL the user should be redirected to, for authorizing.
     */
    public function authorize(): string {
        return $this->oauth2Provider->getAuthorizationUrl();
    }

    /**
     * Exchanges an authorization code for an access token and stores it.
     *
     * @throws TokenException
     * @throws ConnectionException
     */
    public function finishAuthorize(string $code): void {
        $this->tokenManager->exchangeAuthorizationCode($code);
    }

    /**
     * Simple method that just checks if API requests can be made
     *
     * @throws ApiException
     * @throws TokenException
     * @throws ConnectionException
     */
    public function ping(): mixed {
        return $this->apiClient->get('ping');
    }

    public function transaction(): TransactionService {
        if (null === $this->transactionService) {
            $this->transactionService = new TransactionService($this->apiClient);
        }
        return $this->transactionService;
    }

    public function subscription(): SubscriptionService {
        if (null === $this->subscriptionService) {
            $this->subscriptionService = new SubscriptionService($this->apiClient);
        }
        return $this->subscriptionService;
    }

    public function payment(): PaymentService {
        if (null === $this->paymentService) {
            $this->paymentService = new PaymentService($this->apiClient);
        }
        return $this->paymentService;
    }

    public function gateway(): GatewayService {
        if (null === $this->gatewayService) {
            $this->gatewayService = new GatewayService($this->apiClient);
        }
        return $this->gatewayService;
    }

    /**
     * Applies defaults, rejects an incomplete option array, and normalises the
     * values the rest of the constructor treats as always present.
     *
     * @param array $options
     * @return array
     */
    private function resolveOptions(TokenStorageInterface $tokenStorage, array $options): array {
        $required = ['client_id'];
        if (!$tokenStorage instanceof StaticToken) {
            // Redirect URI is not needed for static tokens
            $required[] = 'redirect_uri';
        }

        $missing = array_diff_key(array_flip($required), $options);
        if (!empty($missing)) {
            throw new \InvalidArgumentException(
                'Required options not defined: ' . implode(', ', array_keys($missing))
            );
        }

        $options = array_merge([
            'base_uri' => 'https://api.onpay.io',
            'base_authorize_uri' => 'https://manage.onpay.io',
        ], $options);

        // Set redirect_uri to an empty value if none is sent
        $options['redirect_uri'] ??= '';
        $options['platform'] ??= 'php-sdk' . '/' . self::SDK_VERSION;

        return $options;
    }

    /**
     * league/oauth2-client talks to the token endpoint through Guzzle. When the
     * injected PSR-18 client happens to be Guzzle, hand it over so both paths
     * share one client; otherwise let the provider build its own.
     *
     * @return array
     */
    private function providerCollaborators(ClientInterface $httpClient): array {
        if (
            interface_exists('GuzzleHttp\ClientInterface')
            && $httpClient instanceof \GuzzleHttp\ClientInterface
        ) {
            return ['httpClient' => $httpClient];
        }

        return [];
    }
}
